[package]
name = "geekymedic-tools"
version = "0.1.0"
authors = ["huarong.zheng <huarong.zheng@geekymedic.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
